version: "3"
services:
  casdoor:
    container_name: casdoor
    image: casbin/casdoor:latest
    ports:
      - "8000:8000"
    volumes:
      - ./data:/data # Mount data directory
      - ./conf:/conf
      - ./logs:/logs
    environment:
      - GIN_MODE=release
    restart: unless-stopped
    depends_on:
      - postgres
    networks:
      - shared_network
  postgres:
    image: postgres:15-alpine
    container_name: casdoor-postgres
    environment:
      - POSTGRES_USER=casdoor
      - POSTGRES_PASSWORD=casdoorpw.
      - POSTGRES_DB=casdoor
    ports:
      - "5432:5432"
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    command:
      - "postgres"
      - "-c"
      - "shared_buffers=256MB"
    restart: unless-stopped
    networks:
      - shared_network
networks:
  shared_network:
    external: true
