version: "3"
services:
  casdoor:
    container_name: casdoor
    image: casbin/casdoor:latest
    ports:
      - "8000:8000"
    volumes:
      - ./data:/data # Mount data directory
      - ./conf/app.conf:/conf/app.conf
    environment:
      - RUNNING_IN_DOCKER=true
    restart: unless-stopped
